### Get all items
GET http://localhost:3000/songs
Accept: application/json

### Get a single item by ID
GET http://localhost:3000/songs/1
Accept: application/json

### Create a new item
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "NewSong", // string
    "artist": "ArtistName", // string[]
    // "releaseDate": "yyyy-mm-dd",
    // "duration": "hh:mm"
}

### Update an existing item
PUT http://localhost:3000/songs/1
Content-Type: application/json

{
    "name": "UpdatedSong",
    "description": "This song has been updated"
}

### Delete an item
DELETE http://localhost:3000/songs/3